services:
- type: web
  name: agriscan-ai
  env: python
  runtime: python
  pythonVersion: 3.10         
  buildCommand: pip install -r requirements.txt
  startCommand: streamlit run streamlit_app.py --server.port $PORT --server.headless true
